import { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Poulet Entier Frais",
    description: "Poulet entier frais de qualité supérieure, élevé localement. Idéal pour les grillades et rôtis familiaux.",
    pricePerKg: 2500,
    pricePerUnit: 4500,
    image: "/images/poulet-entier.jpg",
    stock: 150,
    category: "entier",
    popular: true,
  },
  {
    id: "2",
    name: "Poulet Fermier Bio",
    description: "Poulet fermier élevé en plein air, nourri aux céréales naturelles. Goût authentique garanti.",
    pricePerKg: 4000,
    pricePerUnit: 7000,
    image: "/images/poulet-fermier.jpg",
    stock: 80,
    category: "fermier",
    popular: true,
  },
  {
    id: "3",
    name: "Cuisses de Poulet",
    description: "Cuisses de poulet découpées avec soin. Parfaites pour le yassa poulet et les braisés.",
    pricePerKg: 3000,
    pricePerUnit: 2000,
    image: "/images/cuisses-poulet.jpg",
    stock: 200,
    category: "decoupe",
    popular: true,
  },
  {
    id: "4",
    name: "Ailes de Poulet",
    description: "Ailes de poulet fraîches, idéales pour les fritures et marinades épicées.",
    pricePerKg: 2800,
    pricePerUnit: 1500,
    image: "/images/ailes-poulet.jpg",
    stock: 300,
    category: "decoupe",
  },
  {
    id: "5",
    name: "Poulet Congelé Entier",
    description: "Poulet entier congelé pour une conservation longue durée. Qualité préservée.",
    pricePerKg: 2200,
    pricePerUnit: 3800,
    image: "/images/poulet-congele.jpg",
    stock: 500,
    category: "congele",
  },
  {
    id: "6",
    name: "Blancs de Poulet",
    description: "Filets de poulet maigres et tendres. Parfaits pour les régimes et plats sains.",
    pricePerKg: 3500,
    pricePerUnit: 2500,
    image: "/images/blancs-poulet.jpg",
    stock: 120,
    category: "decoupe",
    popular: true,
  },
  {
    id: "7",
    name: "Poulet Fermier Label",
    description: "Poulet fermier label rouge, élevé pendant 81 jours minimum. Chair ferme et savoureuse.",
    pricePerKg: 4500,
    pricePerUnit: 8000,
    image: "/images/poulet-fermier-label.jpg",
    stock: 50,
    category: "fermier",
  },
  {
    id: "8",
    name: "Pilons Congelés",
    description: "Pilons de poulet congelés en sachet. Pratiques et économiques pour la famille.",
    pricePerKg: 2000,
    pricePerUnit: 1200,
    image: "/images/pilons-congeles.jpg",
    stock: 400,
    category: "congele",
  },
];
